import { Button, VerticalBox, ProgressIndicator} from "std-widgets.slint";

export component AppWindow inherits Window {
    width: 400px;
    height: 400px;

    // Variables shared between front and back end
    in-out property <string> inp_dir;
    in-out property <string> out_dir;
    in-out property <string> success_msg;
    in-out property <string> err_msg;
    in-out property <float> conv_progress;

    // Backend function calls
    callback select-dir(int);
    callback to-jpeg(string, string);
    callback update_prog_ind();

    // GUI markup
    VerticalBox {
        Text {
            text: "Current input folder:\n\{root.inp_dir}";
        }

        Button {
            text: "Select input folder";
            clicked => {
                root.select-dir(0);
            }
        }

        Text {
            text: "Current output folder:\n\{root.out_dir}";
        }

        Button {
            text: "Select output folder";
            clicked => {
                root.select-dir(1);
            }
        }

        ProgressIndicator {
            height: 40px;
            width: 380px;
            padding-left: 10px;
            progress: conv_progress;
        }

        Button {
            text: "Convert images to jpeg";
            clicked => {
                root.to-jpeg(inp_dir, out_dir);
            }
        }

        // Success text
        Text {
            text: "\{root.success_msg}";
        }
        
        // Error loggin text
        Text {
            text: "\{root.err_msg}";
        }
    }
}
